# Page settings
baseurl = "/"
title = "Dreamly"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableRobotsTXT = true
canonifyURLs = true
minify = true
[params]

# 5. Make it possible to add CMS for content editing
# 6. Remove jQuery
# 7. Remove bootstrap
# 8. Remove icomoon for fontawesome
# 9. Fix bugs & check browser compatibility

  custom_css = []

  # Meta
  twitter_handle = "@team_dreamly"
  author = "Dreamly"
  description = "Enabling your dream by providing cutting edge IT services"
  title = "Invigorating dreams"
  email = "info@dreamly.se"
  # Languages
  tags = ["IT","Software","Web","Consulting","Infrastructure","Apps","iOS","Android","Website","App"]

[languages]
  [languages.en]
  languageName = "English"
  weight = 1.0


  [languages.se]
  languageName = "Svenska"
  weight = 2.0

  [languages.jp]
  languageName = "日本語"
  weight = 3.0
  # Navigation
  [params.navigation]
    brand = "dreamly"
    home = "home.title"
    services = "services.title"
    missions = "missions.title"
    about = "about.title"
    contact = "contact.title"

  # Hero section
  [params.hero]
    title = "hero.title"
    subtitle = 'hero.subtitle'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "intro.plan.title"
    description = "intro.plan.description"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "intro.develop.title"
    description = "intro.develop.description"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "intro.launch.title"
    description = "intro.launch.description"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "intro.movie.title"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # mission section
  [params.missions]
    enable = true
    title = "missions.title"
    description = "missions.description"
    background = "full_image_3.jpg"

    [[params.missions.item]]
      title = "missions.innovate.title"
      description = "missions.innovate.description"
      icon = "icon-map-marker"

    [[params.missions.item]]
      title = "missions.equality.title"
      description = "missions.equality.description"
      icon = "icon-users"
    [[params.missions.item]]
      title = "missions.contribute.title"
      description = "missions.contribute.description"
      icon = "icon-globe"

      [[params.missions.item]]
      title = "missions.social.title"
      description = "missions.social.description"
      icon = "icon-home"

  # Services section
  [params.services]
    enable = true
    title = "services.title"
    description = "services.description"
    background = "full_image_3.jpg"

    [[params.services.item]]
      title = "services.design.title"
      description = "services.design.description"
      icon = "icon-edit"

    [[params.services.item]]
      title = "services.software.title"
      description = "services.software.description"
      icon = "icon-cog"
    [[params.services.item]]
      title = "services.hosting.title"
      description = "services.hosting.description"
      icon = "icon-server"

      [[params.services.item]]
      title = "services.other.title"
      description = "services.other.description"      
      icon = "icon-question"

  # About section
  [params.about]
    enable = true
    title = "about.title"
    description = "about.description"

    [[params.about.item]]
      name = "about.lars.name"
      position = "about.lars.position"
      description = "about.lars.description"
      img = "lars.jpeg"
      alt = "about.lars.alt"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/larssonlars/"],
        ["icon-github", "http://github.com/lalarsson"],
        ["icon-envelope", "lars@dreamly.se"]
      ]
    [[params.about.item]]
      name = "about.takeshita.name"
      position = "about.takeshita.position"
      description = "about.takeshita.description"
      img = "takeshita.jpg"
      alt = "about.takeshita.alt"
      social = [
        ["icon-envelope", "takeshita@dreamly.se"]
      ]
    # [[params.about.item]]
    #   name = "about.hamakawa.name"
    #   position = "about.hamakawa.position"
    #   description = "about.hamakawa.description"
    #   img = "hamakawa.png"
    #   alt = "about.hamakawa.alt"
    #   social = [
    #   ]
    [[params.about.item]]
      name = "about.roger.name"
      position = "about.roger.position"
      description = "about.roger.description"
      img = "roger.png"
      alt = "about.roger.alt"
      social = [
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "counters.title"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "counters.projects"
      icon = "icon-briefcase"
      from = 0
      to = 3
      interval = 1
      speed = 1000

    [[params.counters.item]]
      description = "counters.lines"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "counters.cutlery"
      icon = "icon-cutlery"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "counters.clients"
      icon = "icon-users"
      from = 0
      to = 3
      interval = 1
      speed = 1000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "contact.title"
    description = "contact.description"
    
    # Available icons: http://simplelineicons.com/
    details = [
        # ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        # ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@dreamly.se"],
        ["icon-twitter", "@team_dreamly"],
        ["icon-facebook", "@teamdreamly"],
        #["icon-youtube", "https://www.youtube.com/channel/UCi3OcZBNtQbLXaj5Vniv16Q"],
        ["icon-instagram", "team_dreamly"],
        ["icon-linkedin", "https://www.linkedin.com/company/dreamly/"]
      ]

    name = "contact.name"
    email = "contact.email"
    phone = "contact.phone"
    message = "contact.message"
    button = "contact.button"
