version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk update && apk  --update add git  nodejs
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      - run:
          name: PostCSS
          command: |
            npm install
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      # - run:
      #     name: Test static files
      #     command: |
      #       htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
      #       --empty-alt-ignore --disable-external
      - deploy:
          name: Deploy
          command: bash scripts/deploy.sh
